### ISSUE TITLE
What is the behavior by conflicting imports?

### ISSUE THREAD

**Issue by themetalone** [oasp/ts-merger#11]
I have two different cases for which I have no clue on how the merger should behave. Could you clarify what the behavior should be (for `patchOverride` true and false)? 

* Import Test Case 6:
  * base ``import { a as b } from 'c';``
  * patch ``import { a as d } from 'c';``

* Import Test Case 7:
  * base ``import { a as b } from 'c';``
  * patch ``import { d as b } from 'c';``

Thx :)

**Comment by EastWindShak** [comment]
This case is not currently covered, but obviously it should. Skip this test for the moment.
