### ISSUE TITLE
Merge of Decorators

### ISSUE THREAD

**Issue by themetalone** [oasp/ts-merger#17]
Hello, 

Could you specify on how the ts-merger handles decorators and if the `@NgModule` is still a special case in the algorithm

(Class test cases 9 and 10)

**Comment by EastWindShak** [comment]
NgModule is no more a special case. Decorators would be merged taking account the argumentes. If tthe argument is ObjectLiteral or ArrayLiteral, other cases will keep base arguments if no patchOverrides or patch arguments if patchOverrides

**Comment by themetalone** [comment]
So the argument is also merged if it is an array or an object?

**Comment by EastWindShak** [comment]
Correct

**Comment by themetalone** [comment]
Just to have it online, the behavior of the decorator merge according to our talk, as far as I understood: 
Decorators are accumulated
If a decorator is present in base and patch AND
* it has a 'primitive' or more than one argument: the arguments are chosen according to the `patchOverride` flag
* it has exactly one object or array: the object/array is merged by accumulating the fields/entries. 

Is that correct?

**Comment by EastWindShak** [comment]
yes, that's correct
