### ISSUE TITLE
Release to @oasp npm organisation

### ISSUE THREAD

**Issue by maybeec** [oasp/ts-merger#18]
At the end of June, we should have a release on npm repository under the `@oasp` organisation like https://www.npmjs.com/package/@oasp/oasp4fn

**Comment by maybeec** [comment]
Please make sure, that this repository maintains git tags for each release. On npmjs I already see four releases but no git tags here!

**Comment by EastWindShak** [comment]
The problem with npm is that every minor change, (including ReadME changes) must be repusblished as a new version. NPM does not allow rewrite a version.

**Comment by EastWindShak** [comment]
Working version released at https://www.npmjs.com/package/@oasp/ts-merger
