### ISSUE TITLE
merge of decorators with multiple arguments broken

### ISSUE THREAD

**Issue by themetalone** [oasp/ts-merger#19]
Corresponding Class test case 15:
given the decorators
* base 
```typescript
@decorator("a","b")
```
* patch
```typescript
@decorator("c","d")
```

yields 
```typescript
@decorator('a''b')
// or 
@decorator('c''d')
```
Note the missing comma between the arguments.

**Comment by maybeec** [comment]
How can it be OR?
Is the current algorithm non-deterministic?

**Comment by themetalone** [comment]
OR depending on the value of `patchOverride` (true or false)
