### ISSUE TITLE
setup travis for running tests

### ISSUE THREAD

**Issue by EastWindShak** [oasp/ts-merger#3]
_From @maybeec on May 5, 2017 6:59_

_Copied from original issue: EastWindShak/tsm#3_

**Comment by EastWindShak** [comment]
Indeed,  the test are configured using Mocha and Chai

**Comment by maybeec** [comment]
might be good to have this in place as soon as possible as @themetalone already started to implement tests. :)

**Comment by EastWindShak** [comment]
yep, I have already merger his PR's
