### ISSUE TITLE
no imports merge when base is empty

### ISSUE THREAD

**Issue by themetalone** [oasp/ts-merger#9]
It seems that the merger skips the merge of the imports when the base file is empty. When the patch file is empty the merge works as expected

Test Case 5 of the import tests corresponds to this

**Comment by EastWindShak** [comment]
@themetalone is this solved?

**Comment by themetalone** [comment]
doesn't look so

see [travis current build](https://travis-ci.org/oasp/ts-merger/builds/243558011#L546) there is still an empty output from the merger

**Comment by EastWindShak** [comment]
but this issue was about the merger does not adds patch imports if base file is empty. Is this still not working?

**Comment by themetalone** [comment]
According to the tests not. 

Since the algorithm gives the merge result to the console output you can see that at failure `5)` there is nothing (or an empty line) in the log (above the failure 5)

**Comment by EastWindShak** [comment]
Oh I see. I was seeing the wrong test. Working on it.

**Comment by EastWindShak** [comment]
now it should work
